// constants.js
export const initialData = [
  {
    firstName: 'John',
    lastName: 'Doe',
    address: '261 Erdman Ford',
    city: 'East Daphne',
    state: 'Kentucky',
  },
  {
    firstName: 'Jane',
    lastName: 'Doe',
    address: '769 Dominic Grove',
    city: 'Columbus',
    state: 'Ohio',
  },
  {
    firstName: 'Joe',
    lastName: 'Doe',
    address: '566 Brakus Inlet',
    city: 'South Linda',
    state: 'West Virginia',
  },
  {
    firstName: 'Kevin',
    lastName: 'Vandy',
    address: '722 Emie Stream',
    city: 'Lincoln',
    state: 'Nebraska',
  },
  {
    firstName: 'Joshua',
    lastName: 'Rolloffs',
    address: '32188 Larkin Turnpike',
    city: 'Charleston',
    state: 'South Carolina',
  },
  {
    firstName: 'Emily',
    lastName: 'Johnson',
    address: '15 Oak Avenue',
    city: 'Portland',
    state: 'Oregon',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    address: '789 Pine Street',
    city: 'Denver',
    state: 'Colorado',
  },
  {
    firstName: 'Sarah',
    lastName: 'Wilson',
    address: '456 Maple Drive',
    city: 'Austin',
    state: 'Texas',
  },
  {
    firstName: 'David',
    lastName: 'Miller',
    address: '321 Cedar Lane',
    city: 'Phoenix',
    state: 'Arizona',
  },
  {
    firstName: 'Lisa',
    lastName: 'Garcia',
    address: '654 Birch Road',
    city: 'Seattle',
    state: 'Washington',
  },
  {
    firstName: 'Robert',
    lastName: 'Martinez',
    address: '987 Elm Court',
    city: 'Miami',
    state: 'Florida',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Anderson',
    address: '147 Spruce Way',
    city: 'Boston',
    state: 'Massachusetts',
  },
];
